/** Firestore collection name constants (camelCase paths matching firestore.rules). */
export const COLLECTIONS = {
  users: 'users',
  profiles: 'profiles',
  studentProfiles: 'studentProfiles',
  userSettings: 'userSettings',
  userPreferences: 'userPreferences',
  userRoles: 'userRoles',
  universities: 'universities',
  brands: 'brands',
  categories: 'categories',
  offers: 'offers',
  claimedOffers: 'claimedOffers',
  savedOffers: 'savedOffers',
  favorites: 'favorites',
  purchases: 'purchases',
  partnershipRequests: 'partnershipRequests',
  experiencePosts: 'experiencePosts',
  experiencePostComments: 'comments',
  experiencePostLikes: 'likes',
  supportTickets: 'supportTickets',
  verificationRequests: 'verificationRequests',
  teamInvites: 'teamInvites',
  activityLog: 'activityLog',
  abAssignments: 'abAssignments',
  abEvents: 'abEvents',
  emailSendLog: 'emailSendLog',
  emailQueue: 'emailQueue',
  emailSendState: 'emailSendState',
  emailUnsubscribeTokens: 'emailUnsubscribeTokens',
  suppressedEmails: 'suppressedEmails',
  favoriteBrandAlertsSent: 'favoriteBrandAlertsSent',
  publicStats: 'publicStats',
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
